#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages: 
  - neofetch
  - tmux

runcmd:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
  - sudo apt-get update 
  - sudo ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev -y
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/azureuser/.bash_profile
  - echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/azureuser/.bashrc